version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
      - media:/app/media/
  backend:
    depends_on:
      - db
    image: ekaterinarez/foodgram_backend
    env_file:
      - .env
    volumes:
      - static:/backend_static
      - media:/app/media/

  frontend:
    image: ekaterinarez/foodgram_frontend
    env_file:
      - .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    depends_on:
      - backend
      - frontend
    image: ekaterinarez/foodgram_gateway
    env_file:
      - .env
    volumes:
      - static:/staticfiles/
      - media:/app/media/
    ports:
      - 8000:80