# Generated by Django 3.2.3 on 2024-12-03 14:55

from django.db import migrations, models
import shortlink.models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshort',
            name='short_url',
            field=models.CharField(default=shortlink.models.generate_short_url, max_length=7, unique=True),
        ),
    ]
