# Generated by Django 3.2.3 on 2024-12-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlshort',
            options={'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.AlterField(
            model_name='urlshort',
            name='short_url',
            field=models.URLField(unique=True),
        ),
    ]
