# Generated by Django 3.2.3 on 2024-12-04 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0002_alter_urlshort_short_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlshort',
            options={'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
    ]
