# Generated by Django 3.2.3 on 2024-12-02 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredients_measurement_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientsforrecipe',
            old_name='count',
            new_name='amount',
        ),
    ]
