# Generated by Django 3.2.3 on 2024-12-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_ingredient_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_url',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
