# Generated by Django 3.2.3 on 2024-12-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_count_ingredientsforrecipe_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(help_text='Выберите изображение', upload_to='media/', verbose_name='Изображение'),
        ),
    ]
