# Generated by Django 3.2.3 on 2024-12-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20241206_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Выберите изображение', upload_to='recipes/', verbose_name='Изображение'),
        ),
    ]
