# Generated by Django 3.2.3 on 2024-12-24 10:32

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(help_text='Выберите теги', related_name='recipes', to='recipes.Tag', validators=[core.validators.RecipeValidators.tags_validator], verbose_name='Теги'),
        ),
    ]
